
package main.gui;
import java.util.List;
//import javax.swing.event.TableModelEvent;
//import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import main.java.*;
import javax.swing.table.TableRowSorter;
import javax.swing.table.TableModel;
public class LoginHistory extends javax.swing.JPanel {
    Frame frame;
    private String resource="src/main/resource/userLog.txt";
    //private TableRowSorter<TableModel> rowSorter;
    private DefaultTableModel loginHistoryTableModel;
    public LoginHistory() {
        initComponents();
        
    }
    
    public void setFrame(Frame frame) {
        this.frame = frame;
    }
    public void initAdditionalComponents(){
        loginHistoryTableModel = (DefaultTableModel)tblLoginHistory.getModel();
        loginHistoryTableModel.setRowCount(0);
//        if(tblLoginHistory.getRowCount() > 0){
//            for (int i=tblLoginHistory.getRowCount()- 1; i >= 0; i--){
//                loginHistoryTableModel.removeRow(i); 
//            }
//        }
        //rowSorter = new TableRowSorter<>(tblLoginHistory.getModel());
        
        List<String> loginHistoryData = DAO.readAll(resource);
        
        
        for(String line:loginHistoryData){
                String[] dataRow = line.split(";"); 
                loginHistoryTableModel.addRow(dataRow);
        }
        
        //TableSortFilter.addFilter(rowSorter, tblLoginHistory, txtSearchHistory);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoginHistory = new javax.swing.JTable();
        lblLoginHistory = new javax.swing.JLabel();
        btnReturnMenu = new javax.swing.JButton();
        btnClearHistory = new javax.swing.JButton();

        tblLoginHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Name", "Role", "Login Time", "Logout Time", "Login Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLoginHistory);

        lblLoginHistory.setText("Login History");

        btnReturnMenu.setText("Back to Menu");
        btnReturnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnMenuActionPerformed(evt);
            }
        });

        btnClearHistory.setText("Clear History");
        btnClearHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClearHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(410, 410, 410)
                .addComponent(btnReturnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(lblLoginHistory))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(lblLoginHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClearHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnReturnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnMenuActionPerformed
        this.frame.changePages(1);
    }//GEN-LAST:event_btnReturnMenuActionPerformed

    private void btnClearHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearHistoryActionPerformed
        DAO.clear(resource);
        loginHistoryTableModel.setRowCount(0);
    }//GEN-LAST:event_btnClearHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearHistory;
    private javax.swing.JButton btnReturnMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLoginHistory;
    public javax.swing.JTable tblLoginHistory;
    // End of variables declaration//GEN-END:variables
}
