package main.gui;


import main.java.*;

public class UserLogin extends javax.swing.JPanel {

    public UserLogin() {
        initComponents();
        lblInvalidCredentials.setVisible(false);
    }
    public void setFrame(Frame frame) {
        this.frame = frame;
    }
    public void clearInvalidCredentials(){
        lblInvalidCredentials.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsernameLogin = new javax.swing.JTextField();
        txtPasswordLogin = new javax.swing.JPasswordField();
        lblInvalidCredentials = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        lblInvalidCredentials.setForeground(new java.awt.Color(255, 51, 51));
        lblInvalidCredentials.setText("Invalid Username & Password");
        lblInvalidCredentials.setToolTipText("");

        btnLogin.setLabel("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(txtUsernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(txtPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(540, 540, 540)
                .addComponent(lblInvalidCredentials))
            .addGroup(layout.createSequentialGroup()
                .addGap(560, 560, 560)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(txtUsernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(txtPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblInvalidCredentials)
                .addGap(16, 16, 16)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        if (user.authenticate(txtUsernameLogin.getText(),String.valueOf(txtPasswordLogin.getPassword()))==true){
            if ("A".equals(user.getRole())){  
                admin.setUsername(user.getUsername());
                admin.setName(user.getName());
                admin.setAge(user.getAge());
                admin.setPassword(user.getPassword());
                admin.setSex(user.getSex());
                this.frame.adminMenu.setAdmin(this.admin);
                this.frame.changePages(1);

            }else{
                customer.setUsername(user.getUsername());
                customer.setName(user.getName());
                customer.setAge(user.getAge());
                customer.setPassword(user.getPassword());
                customer.setSex(user.getSex());
                this.frame.customerMenu.setCustomer(this.customer);
                this.frame.changePages(2);
            }
            txtUsernameLogin.setText("");
            txtPasswordLogin.setText("");
        }else{
            lblInvalidCredentials.setVisible(true);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblInvalidCredentials;
    private javax.swing.JPasswordField txtPasswordLogin;
    private javax.swing.JTextField txtUsernameLogin;
    // End of variables declaration//GEN-END:variables
    User user=new User();
    Admin admin=new Admin();
    Customer customer=new Customer();
    Frame frame;
    
}

