package main.gui;


import main.java.*;

public class userLogin extends javax.swing.JPanel {

    public userLogin() {
        initComponents();
        lblInvalidCredentials.setVisible(false);
    }
    public void setFrame(frame frame) {
        this.frame = frame;
    }
    public void clearInvalidCredentials(){
        lblInvalidCredentials.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsernameLogin = new javax.swing.JTextField();
        txtPasswordLogin = new javax.swing.JPasswordField();
        lblInvalidCredentials = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtUsernameLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 270, 39));
        add(txtPasswordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 270, 40));

        lblInvalidCredentials.setForeground(new java.awt.Color(255, 51, 51));
        lblInvalidCredentials.setText("Invalid Username & Password");
        lblInvalidCredentials.setToolTipText("");
        add(lblInvalidCredentials, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, -1, -1));

        btnLogin.setLabel("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 102, 38));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        if (user.authenticate(txtUsernameLogin.getText(),String.valueOf(txtPasswordLogin.getPassword()))==true){
            if ("A".equals(user.getRole())){  
                admin.setUsername(user.getUsername());
                admin.setName(user.getName());
                admin.setAge(user.getAge());
                admin.setPassword(user.getPassword());
                admin.setSex(user.getSex());
                this.frame.adminMenu1.setAdmin(this.admin);
                this.frame.changePages(1);

            }else{
                customer.setUsername(user.getUsername());
                customer.setName(user.getName());
                customer.setAge(user.getAge());
                customer.setPassword(user.getPassword());
                customer.setSex(user.getSex());
                this.frame.customerMenu3.setCustomer(this.customer);
                this.frame.changePages(2);
            }
            txtUsernameLogin.setText("");
            txtPasswordLogin.setText("");
        }else{
            lblInvalidCredentials.setVisible(true);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblInvalidCredentials;
    private javax.swing.JPasswordField txtPasswordLogin;
    private javax.swing.JTextField txtUsernameLogin;
    // End of variables declaration//GEN-END:variables
    User user=new User();
    Admin admin=new Admin();
    Customer customer=new Customer();
    frame frame;
    
}

